### ISSUE TITLE
tool

### ISSUE THREAD

**Issue by bhasenes** [lepelog/skywardsword-tools#2]
Hello, how to use this tool, is there a guide?

**Comment by elijah-thomas774** [comment]
this repo is more to tools analyze the game more. the output branch contains the files that have been analyzed. Im not sure if this is the type of tool you are looking for, but the wiki on this repo has a link to the object map which displays all objects and our currently documented info per map in game

**Comment by bhasenes** [comment]
Well, I want to translate this game into my own language. Can I use this tool for this purpose or do you have any tools you recommend?

**Comment by elijah-thomas774** [comment]
Translate? how so?
if you mean like text Im not sure if there are any tools directly to handle things all at once, but if you head to the ssrando discord server from https://ssrando.com/ there are modding channels and discussion for reverse engineering the game. I know some people have changed the text to how they see fit.

**Comment by bhasenes** [comment]
I'm on the Diskord server and I'll contact you from there, thank you very much.
